title : Public Private Sector

safe: true
lsi: false
pygments: true
auto: true

source: government-services
destination: government-services

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 1000
paginate_path: "/blog/page:num"

production_url : http://government.services.publicprivatesector.org/

BASE_PATH : http://government.services.publicprivatesector.org/

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
