title : Public Private Sector

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

source: government-services
destination: government-services

paginate_path: "/blog/page:num"

production_url : http://government.services.adopta.agency

BASE_PATH : http://government.services.adopta.agency

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
